irods/irods_resource_plugin_s3

README, s3/libirods_s3.cpp
Howdy,
There are several different on-prem object stores that speak S3 (Openstack Swift, etc.) now, besides Amazon's.  Since these stores are on a private network/VLAN, unencrypted HTTP connections are sometimes used instead of HTTPS.
The small change here adds a per-resource configurable parameter, S3_PROTO, which lets the administrator choose HTTP or HTTPS at resource creation time.  It defaults back to the original behavior when nothing is specified (HTTPS), so it should be 100% backward compatible with any existing installations.
Would you consider merging this option into your main tree?
Thanks,
-Earle F. Philhower, III
=> Add in HTTP/HTTPS selection at resource creation time

s3/libirods_s3.cpp, s3/libirods_s3.hpp
The prior multipart/multithread patch did not use a multipart copy operation, and would fail on Amazon objects of > 5GB in size.  This patch adds that capability automatically for objects which are larger than the multipart chunk size.
It's much smaller a change than it looks because there are a lot of whitespace diffs because of the "if(OK) { if (OK) { if (OK) { ... } } } } } return status;" coding style it started with.    The whole s3CopyObject() changes are only maybe 5 lines, the rest are indents due to an add'l if() level needed for the object size read.
You will need the latest libs3 from yesterday with the new S3_copy_object_range() API added to compile and run successfully.
Also demoted some minor performance stats to DEBUG log level to keep chattiness down.
=> Multipart, parallel copy of objects

packaging/test_irods_resource_plugin_s3.py, s3/libirods_s3.cpp
[1855] Test move when decoupled naming when vault path is just the bucket name.  Add setting the physical_path when not using decoupled naming.
=> Issue 1855

s3/libirods_s3.cpp
Fixed the stomping of the detailed error message when the keypair file is not found.
=> [1903] Fixed the stomping of error message (master)

s3/libirods_s3.cpp
Fixed the stomping of the detailed error message when the keypair file is not found.
=> [1903] Fixed the stomping of error message (4-2-stable)

irods_consortium_continuous_integration_test_hook.py, packaging/resource_suite_s3_cache.py, packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3_for_cloudian.py, packaging/test_irods_resource_plugin_s3_for_gcp.py
minio-py 7.0.x is not compatible with python2, which is the version of
python used for running the test suites at this time. Lock into the
latest version of the last major version number, which is 6.0.2 until
this is resolved.
Some CI tests are failing, but importing the `minio` module is not the cause. I believe the 3 tests that I see failing are due to some changes in the behavior of the replication API in the server
=> [#1963] Use minio-py version 6.0.2 (4-2-stable)

irods_consortium_continuous_integration_build_hook.py, irods_consortium_continuous_integration_test_hook.py, packaging/test_irods_resource_plugin_s3_ceph.py, packaging/test_irods_resource_plugin_s3_fujifilm.py, packaging/test_irods_resource_plugin_s3_gcs.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/libirods_s3.cpp, s3/s3_operations.cpp, s3/s3_transport/include/managed_shared_memory_object.hpp
=> [irods/irods#3727] Remove ASSERT_* (and bzero) usage (main)

irods_consortium_continuous_integration_test_hook.py, s3/libirods_s3.cpp, s3/s3_operations.cpp
=> Fixes for test hook (4-2-stable)

irods_consortium_continuous_integration_test_hook.py, packaging/resource_suite_s3_cache.py, packaging/resource_suite_s3_nocache.py, s3/s3_operations.cpp
Addresses irods/irods#6154
Addresses irods/irods#6479
Addresses irods/irods#6880
Companion PR: https://github.com/irods/irods/pull/6884
Running tests now.
=> Add tests for data objects stuck in locked status, prevent nullptr dereference (main)

packaging/resource_suite_s3_nocache.py, s3/s3_operations.cpp
This is the same as the one for 4-2-stable except for:
1. The rodsLog() statements have been replaced by the logger.
2. I ran clang format.  (I did not keep the spaces to tabs conversion.)
The tests passed.
=> [2102] Get the number of threads from destination dataObjInp

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/s3_transport/include/s3_transport.hpp
This is a change to reset the thread pool when uploading a large file from a local cache file.  
Notes:
1. The commit for issue 2115 is simply moving some tests to a new class so that they don't get executed in every scenario.  The contents of those tests are unaltered.
2. Before release there will be a new version of libs3 and the CMakeLists.txt for this will need to be updated.  Since I don't know the final hash for that libs3 I can't make the update now.
=> Issue 2114 (main)

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, packaging/test_irods_resource_plugin_s3_ceph.py, packaging/test_irods_resource_plugin_s3_fujifilm.py, packaging/test_irods_resource_plugin_s3_gcs.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/s3_operations.cpp
Update S3 repl test to use checksum.
Do not run S3 repl test when in detached mode as we are using the same bucket for all resources thus the object keys conflict.
=> [2122] Reset global vars after last file closes. (4-2-stable)

packaging/test_irods_resource_plugin_s3_minio.py
This address something that was missed when #2115 was implemented causing minio tests to fail.
Two tests were moved from Test_S3_NoCache_Base to Test_S3_NoCache_Large_File_Tests_Base in that issue.  For the class that derives from Test_S3_NoCache_Large_File_Tests_Base, references to these needed to change in test_irods_resource_plugin_s3_minio.py.  The others were deleted as these methods no longer exist in the base class for them.
=> [2129] Updated reference to large file tests in minio file (4-2-stable)

irods_consortium_continuous_integration_test_hook.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/s3_operations.cpp
This is to address several issues:
- 2110 and 2112 are cherry-picked changes from 4-2-stable into main (with python2 replaced by python3).
- 2128 is needed for a recent change in iRODS core changing size_t to rodsLong_t in file_object::size.
- 2129 addresses something missed in the minio test suite when #2115 was implemented causing minio tests to fail.
I ran this through the testing environment and it passed.
=> Issues 2110 2112 main

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/s3_operations.cpp, s3/s3_transport/include/s3_transport.hpp
Added test cases for large file checksum with MPU disabled. Placed test case in a newly created class so that it only runs for MPU disabled.
Note that this replaces pull request #2132 as I went with a different/simpler approach.
All tests passed.
=> [2124] Be selective when setting open flags on PUT_OPR in s3_file_open_operation() (4-2-stable)

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, packaging/test_irods_resource_plugin_s3_minio.py, s3/s3_operations.cpp, s3/s3_transport/include/s3_transport.hpp
This is a cherry-pick from the one for 4-2-stable.  The only difference is the format of the one added log message.
All tests passed.
=> [2124] Be selective when setting open flags on PUT_OPR in s3_file_ope… (main)

s3/s3_operations.cpp, s3/s3_transport/include/s3_transport.hpp
Addresses #2147
Still needs to be tested against libc++
=> [#2147] use static_cast when instantiating ios_base::openmode with an int

packaging/resource_suite_s3_nocache.py, s3/s3_operations.cpp, s3/s3_transport/include/s3_transport.hpp
This addresses the istream append issues.
I put this on top of #2152.  Once that is merged this will be rebased.
All tests passed.
=> Issues 2151 2153

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, s3/s3_operations.cpp
This fixes issue #2146. All tests passed.
In addition, I added two general test cases to test switching archive naming policy consistent->decoupled and decoupled->consistent after object had already been created. These were added for the following reasons:
1. This is something we should be testing since the physical path in the DB for existing objects should override the archive naming policy.
2. On my first attempt to fix 2146 I broke this behavior and realized there was no specific test for this.
See 03eb431b059802458a2d2ffde02ecdc636295e50 which fixes the scenario I was trying to fix with the open flags.  I am now checking the openType.  This is now working as expected.
=> Issue 2146 main

packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3.py, s3/s3_operations.cpp
This is a cherry-pick of the commits in the previous pull #2159 for 4-2-stable.
Changes:
1. The logger was changed to the old rodsLog() format.
2. The python3 format strings were changed to the old python2 formatting.
3. std::filesystem was changed to boost::filesystem.
This has passed all tests including the manual testing for topology.
=> Issue 2146 42 stable

s3/s3_operations.cpp
This is a fix for the previous pull request.  Somehow in the process of cherry-picking from main and making necessary manual updates, I changed logical_path() to physical_path().  It was missed in testing (which must be done manually) because I accidentally had the resource set to detached mode.
This has passed all testing.
=> [2146] Fixed a physical_path() that should have been a logical_path()

irods_consortium_continuous_integration_build_hook.py
Missed this in #2152
In service of #2138
=> [#2138] Remove libs3 from build hook (main)

irods_consortium_continuous_integration_build_hook.py
Missed this in #2152
In service of #2138
=> [#2138] Remove libs3 from build hook (4-3-stable)

libs3/include/libs3/request_context.h, packaging/resource_suite_s3_cache.py, packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3_for_cloudian.py
Addresses #2180
Addresses #2183
Since this needs to get in for 4.3.2, here is a PR with the non-`alloca()` commits from #2181.
=> [#2180,#2183] Add missing curl include to request_context.h and fix some tests (main)

libs3/include/libs3/request_context.h, packaging/resource_suite_s3_cache.py, packaging/resource_suite_s3_nocache.py, packaging/test_irods_resource_plugin_s3_for_cloudian.py
Addresses #2180
Addresses #2183
Since this needs to get in for 4.3.2, here is a PR with the non-`alloca()` commits from #2182.
=> [#2180,#2183] Add missing curl include to request_context.h and fix some tests (4-3-stable)

packaging/resource_suite_s3_nocache.py, s3_resource/src/s3_operations.cpp, s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is the same as pull request #2199 but with Python3 changes as well as a slight change in output when iput -r is run in 4.3.
=> [2198] Do not blindly set #threads to requested #threads (4-3-stable)

packaging/resource_suite_s3_nocache.py, s3_resource/include/irods/private/s3_resource/multipart_shared_data.hpp, s3_resource/src/s3_operations.cpp, s3_transport/include/irods/private/s3_transport/managed_shared_memory_object.hpp, s3_transport/include/irods/private/s3_transport/multipart_shared_data.hpp, s3_transport/include/irods/private/s3_transport/util.hpp
This pull request addresses two issues:
#2205 - For uploads the number of upload threads must be known.  For PRC transfers with multiprocess uploads, only the first process is setting the keyword for the number of threads.  Since these are multiple processes, this information needs to be saved in multiprocess shared memory so other processes know the correct number of transfer threads/processes.
I created a new shared data segment for the s3 resource which is separate from the s3 transport's shared memory.  I renamed the transport's shared memory so that it is clear which is which.
To know when shared memory can be cleaned up, a counter was added to track the number of closes.  Once the close counter reaches the number of threads the shared memory is cleaned up.  I have verified that when …
=> Issue 2205 - 4-3-stable

irods_consortium_continuous_integration_test_hook.py, packaging/resource_suite_s3_nocache.py
Replace all instances of assertEquals with assertEqual 
Do not install unittest-xml-reporting==1.14.0
Version-sniff to avoid upgrading pip on Ubuntu 24 and later
Needed for testing. Tests pass.
=> [2211,2212,2213] Testing fixes (4-3-stable)

irods_consortium_continuous_integration_test_hook.py, packaging/resource_suite_s3_nocache.py
Replace all instances of assertEquals with assertEqual 
Do not install unittest-xml-reporting==1.14.0
Version-sniff to avoid upgrading pip on Ubuntu 24 and later
=> [2211,2212,2213] Testing fixes (main)

README.md
=> [2216] Updated README.md for troubleshooting checksum read request rate errors (main)

README.md
This change must be applied to 4.3.4.0 (not 4.3.3.1) since the new setting is not valid without the corresponding updates to iRODS.
=> [2216] Updated README.md for troubleshooting checksum read request rate errors (4-3-stable)

packaging/resource_suite_s3_nocache.py
This change to the test allows a full test run to pass against iRODS 4.3.4.
Still need to determine what caused a change in the error code.
=> [#2225] Change expected error code in test (4-3-stable)

packaging/resource_suite_s3_nocache.py
Confirmed the test still passes.
Wording taken from commits for irods/irods#7990.
Will pound shortly.
=> [#2225] Change test to also accept USER_SOCK_CONNECT_ERR (4-3-stable)
