irods/irods_resource_plugin_s3

- packaging/resource_suite_s3_nocache.py
- s3/s3_cacheless_operations.cpp
- s3/s3fs/fdcache.cpp
- s3/s3fs/fdcache.h
1) Removed the unnecessary offset_map.clear() from the ~FileOffsetManager() class.
2) Made sure the FileOffsetManager singleton was created last and destroyed first.
3) Replaced a lot of tabs with four spaces.
> Issues 1890 1891 and 1894 (master)

- packaging/resource_suite_s3_nocache.py
- s3/s3_cacheless_operations.cpp
- s3/s3fs/fdcache.cpp
- s3/s3fs/fdcache.h
> Issues 1890 1891 1894 (4-2-stable)

- s3/libirods_s3.cpp
- s3/libirods_s3.hpp
- s3/s3_archive_operations.cpp
- s3/s3_cacheless_operations.cpp
- s3/s3fs/curl.cpp
> Issue 1872

- packaging/resource_suite_s3_nocache.py
could be running tests in a VPN
> [1907] turn off certificate verification in ssl test

- packaging/resource_suite_s3_nocache.py
could be running tests in a VPN
> [#1907] turn off certificate verification in ssl test

- README.md
Happy New Year! 
Hopefully these changes are sensible to you guys. I tried to expand a bit on the expected configuration of the resource as well as points that may be a little confusing to other new users.
> Expanded some areas of the README in an effort to add additional clarity

- s3/s3fs/openssl_auth.cpp
-Wunused-function trips on several static functions in s3fs which
have now been removed.
---
Need to run tests.
> [#1806] Remove unused static functions from s3fs (4-2-stable)

- s3/s3fs/openssl_auth.cpp
-Wunused-function trips on several static functions in s3fs which
have now been removed.
---
Need to run tests.
> [#1806] Remove unused static functions from s3fs (master)

- packaging/resource_suite_s3_nocache.py
- packaging/test_irods_resource_plugin_s3.py
- packaging/test_irods_resource_plugin_s3_for_cloudian.py
- s3/s3fs/openssl_auth.cpp
> 4 2 stable

- packaging/resource_suite_s3_nocache.py
- packaging/test_irods_resource_plugin_s3.py
- packaging/test_irods_resource_plugin_s3_for_cloudian.py
- packaging/test_irods_resource_plugin_s3_for_gcp.py
about specifying minimum number of replicas is deprecated
> [irods/irods4860] Updated test cases for warning message

- CMakeLists.txt
- s3/libirods_s3.cpp
- s3/s3_cacheless_operations.cpp
> [#1932] use replica_status and IRODS_QUERY_ENABLE_SERVER_SIDE_API (4-2-stable)

- CMakeLists.txt
- s3/libirods_s3.cpp
- s3/s3_cacheless_operations.cpp
> [#1932] use replica_status and IRODS_QUERY_ENABLE_SERVER_SIDE_API (master)

- irods_consortium_continuous_integration_build_hook.py
> [#1960] bump libs3 external in buid hook (4-2-stable)

- s3/s3_operations.cpp
> [1987] Passed S3_STSDATE setting to transport

- s3/s3_transport/src/s3_transport.cpp
Fixed check for retryable errors.
> [1999] Fixed retryable check

- s3/s3_transport/src/s3_transport.cpp
Cherry-pick of #2017 into master
> [#1999] Fixed retryable check (master)

- CMakeLists.txt
- irods_consortium_continuous_integration_build_hook.py
- s3/s3_transport/include/s3_transport.hpp
- s3/s3_transport/include/s3_transport_util.hpp
- s3/s3_transport/src/s3_transport.cpp
> [irods/irods_5669, irods/irods_5713] Update for new nlohmann-json

- s3/libirods_s3.cpp
- s3/s3_operations.cpp
Depends on https://github.com/irods/irods/pull/6332
> Updated for variable renaming (main)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
This is to enable Glacier test case.
It is identical to the 4-2-stable except for the one change in the last commit.
> Irods issue 6502 main

- packaging/resource_suite_s3_nocache.py
- s3/s3_operations.cpp
> [2102] Get the number of threads from destination dataObjInp (4-2-stable)

- packaging/resource_suite_s3_cache.py
Addresses irods/irods#6997
Cherry-picked from #2106 
Companion PR: https://github.com/irods/irods/pull/7073
Need to run these tests before merging. No difference between this and 4-2-stable.
> [irods/irods#6997] Add tests for Glacier-only objects (main)

- packaging/resource_suite_s3_cache.py
Addresses irods/irods#6997
@JustinKyleJames - Can you please try this out for me? :)
> [irods/irods#6997] Add tests for Glacier-only objects (4-2-stable)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
Refactor lib.py functions to match those in the main iRODS repo.
> [irods/irods 7152] Refactor lib.py resource functions (main)

- s3_transport/CMakeLists.txt
> [#2186] link `s3_transport_obj` to librt if librt has `shm_open` (main)

- s3_transport/CMakeLists.txt
> [#2186] link `s3_transport_obj` to librt if librt has `shm_open` (4-3-stable)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
- packaging/test_irods_resource_plugin_s3_for_cloudian.py
Addresses #2191 
Still need to run these, but just putting this up for inspection ahead of confirming that tests are passing.
> [#2191] Update tests for replication API changes (4-3-stable)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
- packaging/test_irods_resource_plugin_s3_for_cloudian.py
Addresses #2191
Cherry-picked from #2193
> [#2191] Update tests for replication API changes (main)

- packaging/resource_suite_s3_nocache.py
- s3/s3_operations.cpp
- s3/s3_transport/include/s3_transport.hpp
Test run of the main suite of tests passed.
> [2198] Do not blindly set #threads to requested #threads (4-2-stable)

- packaging/resource_suite_s3_nocache.py
- s3_resource/src/s3_operations.cpp
- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is just a cherry-pick of the commits for 4-3-stable.
> Issue 2198 main

- packaging/resource_suite_s3_nocache.py
- s3_resource/include/irods/private/s3_resource/multipart_shared_data.hpp
- s3_resource/src/s3_operations.cpp
- s3_transport/include/irods/private/s3_transport/managed_shared_memory_object.hpp
- s3_transport/include/irods/private/s3_transport/multipart_shared_data.hpp
- s3_transport/include/irods/private/s3_transport/util.hpp
This is a cherry-pick of PR #2208
> Issue 2205 2207 - MAIN

- packaging/resource_suite_s3_nocache.py
> [#2225] Change test to also accept USER_SOCK_CONNECT_ERR (main)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
- packaging/test_irods_resource_plugin_s3_for_cloudian.py
- s3_resource/src/s3_resource.cpp
Addresses #2231
In service of irods/irods#4685
In service of irods/irods#4861
Companion PR: https://github.com/irods/irods/pull/8285
Need to run tests.
> Change expected output for tests using DataObjTrim (main)

- s3_resource/src/s3_resource.cpp
- s3_transport/include/irods/private/s3_transport/multipart_shared_data.hpp
- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
- s3_transport/src/s3_transport.cpp
Will confirm it builds and I think we can move forward with merging this.
If there are any issues, we can address them after the server is wrapped up.
> [irods/irods#8287] Replace gethostname() with "host" server config option (main)

- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is to fix opens with truncate flag when another thread already opened the cache file.
> [2241] Use file_open_counter to determine open mode if number of threads is unknown (4-3-stable)

- packaging/resource_suite_s3_nocache.py
- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is just cherry-picked from #2242.
This also has the USER_SOCK_CONNECT_ERR change that was done after the 4.3.3 tag.
> Issue 2241 433stable (4-3-3-stable)

- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is a cherry-pick from #2242.
> [2241] Use file_open_counter to determine open mode if number of thre… (main)

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
- s3_resource/include/irods/private/s3_resource/s3_resource.hpp
- s3_resource/src/s3_operations.cpp
- s3_resource/src/s3_resource.cpp
This is to fix test failures for 5.0.
I ran the full suite on an Ubuntu 24 container with Postgres.
> Irods 5 testing

- packaging/resource_suite_s3_cache.py
- packaging/resource_suite_s3_nocache.py
- s3_resource/include/irods/private/s3_resource/s3_resource.hpp
- s3_resource/src/s3_operations.cpp
- s3_resource/src/s3_resource.cpp
This is a cherry-pick of a couple of issues.  I ran the `Test_Compound_With_S3_Resource` and `Test_S3_NoCache_V4` tests against a minio back end.
> Issues cherry pick 43 stables

- CMakeLists.txt
- irods_consortium_continuous_integration_test_hook.py
- packaging/resource_suite_s3_nocache.py
- packaging/s3_prc_upload_issues_2260_2261.py
- s3_resource/src/s3_operations.cpp
- s3_transport/include/irods/private/s3_transport/multipart_shared_data.hpp
- s3_transport/include/irods/private/s3_transport/s3_transport.hpp
This is a cherry-pick of pull request #2259 for 4-3-stable.
All S3 tests were run and passed.
> Issue 2146 (4-3-stable)
